version: '3.8'
services:
  postgres:
    profiles:
      - local
    restart: always
    image: postgres:14.5-alpine
    shm_size: 2gb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: horse_db
    ports:
      - '61791:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  hasura:
    profiles:
      - local
    restart: always
    image: hasura/graphql-engine:v2.24.1
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/horse_db'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/horse_db'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: 'info'
      HASURA_GRAPHQL_ADMIN_SECRET: 'sidneyPassword'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, http-log, webhook-log, websocket-log, query-log'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_SERVER_PORT: 8080
    ports:
      - '61790:8080'
volumes:
  pgdata: {}
