-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "horse_racing_data"."latest_odds" add column "updated_at" timestamp
--  null;
